Fire-Breathing-Rubber-Duck-ies/front-end

- assets/styles/index.scss
- index.html
- package-lock.json
Added non-functioning signin and background animation
> Added signin and background

- assets/styles/index.scss
- index.html
-Added nav bar with add item, sign out and sign in buttons
-Added signup form on first page
> Added nav bar and signup form

- assets/templates/handlebars
- index.html
-Added a modal to input new items
-Linked the modal to the add items button on the nav bar
> Added an input form

- assets/scripts/app.js
- assets/scripts/pagenav/events-pagenav.js
- assets/scripts/pagenav/ui-pagenav.js
- index.html
See commit message for full details about what changed
> Add ability to hide/show things

- index.html
Target credentials[emails] to [email]
Add id="login" to form
> Fix login field capture

- assets/scripts/app.js
- assets/scripts/items/api-items.js
- assets/scripts/items/events-items.js
- assets/scripts/items/ui-items.js
- index.html
See commit message
Coded with jpetrucci49
> Add Create Item

- assets/styles/index.scss
- assets/templates/handlebars
- index.html
-added handlebars form for creating new item
> Added handlebars form

- assets/styles/index.scss
- index.html
-updated background to be covered by one image
-added change password modal and linked it to the change password button in the nav bar
> Updated background and added modal

- assets/scripts/items/api-items.js
- assets/scripts/items/events-items.js
- assets/scripts/items/ui-items.js
Eventus-items.js
- Create function to act after clicked
- Need adjust click handler for handlebars created data
- Need to get name from handlebars information to pass id into api call
api-items.js
- Makes api call to delete item
ui-items.js
- Alerts success or failure
> Add Delete item

- assets/scripts/auth/events-auth.js
- index.html
Index.html
-Change name of change password form inputs
-Change type of new password input to password from text
events-auth.js
- Change click handler to listen for change-pw-form
> Connect change password

- assets/scripts/auth/ui-auth.js
- assets/scripts/items/ui-items.js
- index.html
ui-auth
- Runs function from pageNav ui to hide everything, then show nav Bar
iu-items.js
- Removes hide class from bucket list container upon show all success
index.html
- Add hide class to bucket list card
- Add id to hide bucket list card to be able to use in javascript
> Hide show items at right time

- assets/scripts/items/ui-items.js
- assets/templates/list.handlebars
- index.html
Updated naming from list to item to match backend
> Changed handlebar naming

- assets/scripts/items/ui-items.js
- index.html
Change where the handlesbars tries to load information to
> Change where handlebars points

- assets/scripts/pagenav/events-pagenav.js
- assets/scripts/pagenav/ui-pagenav.js
PageNav Event listener for #to-signout
Hide all elements, Show sign-in prompt
> Link Sign out

- assets/scripts/items/ui-items.js
- assets/templates/individual-item.handlebars
- assets/templates/list.handlebars
-It is now functioning and displays all list items
-It is still missing the checkbox and a separate handlebars file for viewing individual items
> Updated handlebars

- assets/scripts/config.js
https://fbrduckies.herokuapp.com
> Add heroku server link

- assets/scripts/auth/ui-auth.js
- assets/scripts/items/api-items.js
- assets/scripts/items/events-items.js
- assets/scripts/items/ui-items.js
- assets/templates/individual-item.handlebars
- assets/templates/list.handlebars
-linked it to the ui
@jpetrucci49
> Added PATCH

- assets/templates/list.handlebars
Add delete-button class to delete button
> Add Delete class

- assets/scripts/items/events-items.js
> Add range 1-10 for EDIT 'priority'

- assets/scripts/auth/events-auth.js
- assets/scripts/auth/ui-auth.js
- assets/scripts/items/events-items.js
- assets/scripts/items/ui-items.js
-set added item to display after add item success
-fixed sign out button error
> Fixed add item response

- assets/scripts/auth/ui-auth.js
- assets/scripts/items/events-items.js
- index.html
-added clear fields function to sign in, sign up and change password
-changed signup and back classes to ids
@jpetrucci49
> Added clear fields to auth and fixed signup

- assets/styles/index.scss
Update url for background from http:// to https://
> Changed to secure gif

- assets/scripts/auth/ui-auth.js
- assets/scripts/items/events-items.js
- assets/scripts/items/ui-items.js
- assets/styles/index.scss
- index.html
-reset edit form to original content after failed edit submit
> Added form reset

- index.html
> Updated typo on edit modal

- assets/scripts/items/events-items.js
- assets/styles/index.scss
- index.html
-decreased handlebars container top margin
> Decreased top margin

- assets/scripts/items/events-items.js
- assets/styles/index.scss
-added fix background size
-adjusted container margins
> Added fix background

- assets/styles/index.scss
- index.html
-added yellow font and border to titles
> Changed font

- assets/scripts/auth/ui-auth.js
- assets/scripts/items/events-items.js
- assets/scripts/items/ui-items.js
- assets/scripts/pagenav/events-pagenav.js
- assets/styles/index.scss
- index.html
-added second duck to login page
-hid ducks on main page
-cleared fields when switching between sign up and sign in
-toggled nav bar closed after successful log out
> Final edits

- README.md
> Fix wireframe image

- assets/scripts/items/events-items.js
- assets/scripts/items/ui-items.js
- assets/scripts/pagenav/events-pagenav.js
- assets/styles/index.scss
- assets/templates/individual-item.handlebars
- index.html
-Changed some of the ui user facing language
-Changed mouse to pointer when hovering on item name, go to login and go
to sign up
-Removed main page ducks on screen resizing
-Adjusted top margin of content container on resizing
-Toggled nav bar on change pw, and add item success
-Added message to rotate phone when user tries to view individual items
on vertical screen. Content is displayed when phone is rotated
horizontally.
-Fixed login title so that it no longer disappears
-Opened add bucket list item on login success if user has no current
items
> Update UI - lots of stuff
